#
# Product-specific compile-time definitions
# 

TARGET_BOARD_PLATFORM := msm8x25
TARGET_CPU_ABI := armeabi

TARGET_NO_BOOTLOADER := true

TARGET_BOOTLOADER_BOARD_NAME := hwu8825-1

BOARD_KERNEL_CMDLINE := androidboot.hardware=huawei loglevel=1
BOARD_KERNEL_BASE :=

BOARD_BOOTIMAGE_MAX_SIZE :=
BOARD_RECOVERYIMAGE_MAX_SIZE :=
BOARD_SYSTEMIMAGE_MAX_SIZE :=
BOARD_USERDATAIMAGE_MAX_SIZE :=
BOARD_FLASH_BLOCK_SIZE :=

BOARD_HAS_NO_SELECT_BUTTON := true
